name: Apollo-Example
main: com.lunarclient.apollo.example.ApolloExamplePlugin
version: 1.0.5
author: Moonsworth
depend: [ Apollo-Bukkit ]
api-version: 1.13

commands:
    beam:
        description: "Beams!"
    border:
        description: "Borders!"
    chat:
        description: "Chat!"
    coloredfire:
        description: "Colored Fires!"
    combat:
        description: "Combat!"
    cooldown:
        description: "Cooldowns!"
    entity:
        description: "Entity!"
    evnt:
        description: "EVNT!"
    glow:
        description: "Glow!"
    hologram:
        description: "Holograms!"
    limb:
        description: "Limb!"
    modsettings:
        description: "ModSettings!"
    nametag:
        description: "Nametags!"
    notification:
        description: "Notifications!"
    serverrule:
        description: "Server Rule!"
    staffmod:
        description: "Staff Mods!"
    stopwatch:
        description: "Stopwatch!"
    team:
        description: "Teams!"
    title:
        description: "Titles!"
    tntcountdown:
        description: "TNT Countdown!"
    transfer:
        description: "Transfer!"
    vignette:
        description: "Vignette!"
    waypoint:
        description: "Waypoints!"
