name: Apollo-API-Example
main: com.lunarclient.apollo.example.api.ApolloApiExamplePlatform
version: 1.1.8
author: Moonsworth
softdepend: [ Apollo-Bukkit ]
api-version: 1.13

commands:
    apollodebug:
        description: "Apollo Debug!"
    autotexthotkey:
        description: "Auto Text Hotkey!"
    beam:
        description: "Beams!"
    border:
        description: "Borders!"
    chat:
        description: "Chat!"
    coloredfire:
        description: "Colored Fires!"
    combat:
        description: "Combat!"
    cooldown:
        description: "Cooldowns!"
    entity:
        description: "Entity!"
    glint:
        description: "Glint!"
    glow:
        description: "Glow!"
    hologram:
        description: "Holograms!"
    inventory:
        description: "Inventory!"
    limb:
        description: "Limb!"
    modsettings:
        description: "ModSettings!"
    nametag:
        description: "Nametags!"
    nickhider:
        description: "Nick Hider!"
    notification:
        description: "Notifications!"
    richpresence:
        description: "Rich Presence!"
    saturation:
        description: "Saturation!"
    serverrule:
        description: "Server Rule!"
    staffmod:
        description: "Staff Mods!"
    stopwatch:
        description: "Stopwatch!"
    team:
        description: "Teams!"
    tebex:
        description: "Tebex!"
    title:
        description: "Titles!"
    tntcountdown:
        description: "TNT Countdown!"
    transfer:
        description: "Transfer!"
    vignette:
        description: "Vignette!"
    waypoint:
        description: "Waypoints!"
