name: Apollo-Folia
main: com.lunarclient.apollo.ApolloFoliaPlatform
version: 1.1.9
author: Moonsworth
api-version: 1.13
folia-supported: true

commands:
    apollo:
        description: The main Apollo command.
        usage: /apollo <reload|update>
        permission: apollo.command
    lunarclient:
        aliases: [lc]
        description: The command to check whether the player is using Lunar Client.
        usage: /lunarclient <player>
        permission: apollo.lunarclient
