name: Apollo-Bukkit
main: com.lunarclient.apollo.loader.BukkitPlatformLoader
version: 1.0.8
author: Moonsworth
api-version: 1.13
soft-depend: [LunarClient-API]

commands:
  apollo:
    description: The main Apollo command.
    usage: /apollo <reload>
    permission: apollo.command
  lunarclient:
    aliases: [lc]
    description: The command to check whether the player is using Lunar Client.
    usage: /lunarclient <player>
    permission: apollo.lunarclient
